name: Build

on:
  push:
    branches-ignore:
      - main
      - future
jobs:
  deployment:
    name: Build the image
    runs-on: ubuntu-latest
    container: docker
    steps:
      - name: Check out repository code
        uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Serverless image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: serverless-runner:latest
