name: Trivy

on:
  push:
    branches: ["main", "future"]
  pull_request:
    branches: ["main", "future"]
  schedule:
    - cron: "19 7 * * 0"

jobs:
  build:
    name: Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Serverless image from Dockerfile
        run: |
          docker build -t runner-serverless:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner on Serverless image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "runner-serverless:${{ github.sha }}"
          format: "sarif"
          template: "@/contrib/sarif.tpl"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results for Serverless image to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: "trivy-results.sarif"
